### ISSUE TITLE
Support babel 6?

### ISSUE THREAD

**Issue by aaronjensen** [jquense/babel-plugin-jsx-fragment#2]
Looks like the plugin api has changed, any plans to release a babel 6 version?

**Comment by jquense** [comment]
I'm still using Babel 5 for everything so there isn't a ton of need to update for me.  but I'd more then happily take a PR if you want to put it together.

**Comment by aaronjensen** [comment]
Turned out we were only using it in one place and we didn't actually need it, so I just removed it. Feel free to close this if you want, or leave it for documentation purposes :smile: Thanks!
